/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 2011-5-8, 14:44:47
 */
package junchangmis;

import junchangmis.student.*;
import junchangmis.codecSetting.*;

/**
 *
 * @author developers
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("军昌文化艺术学校管理系统");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jLabelTop = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonNewComerIput = new javax.swing.JButton();
        jButtonNewToFormal = new javax.swing.JButton();
        jButtonNewComerTable = new javax.swing.JButton();
        jButtonFormalStuTable = new javax.swing.JButton();
        jButtonDutyTable = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonCode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTop.setBackground(new java.awt.Color(102, 255, 255));
        jLabelTop.setFont(new java.awt.Font("宋体-方正超大字符集", 0, 36));
        jLabelTop.setText("军昌文化艺术学校管理系统");

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(102, 102, 102))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonNewComerIput.setText("试听生信息录入");
        jButtonNewComerIput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewComerIputActionPerformed(evt);
            }
        });

        jButtonNewToFormal.setText("试听生转为正式生");
        jButtonNewToFormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewToFormalActionPerformed(evt);
            }
        });

        jButtonNewComerTable.setText("生成试听生登记表");
        jButtonNewComerTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewComerTableActionPerformed(evt);
            }
        });

        jButtonFormalStuTable.setText("生成交费登记表");
        jButtonFormalStuTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormalStuTableActionPerformed(evt);
            }
        });

        jButtonDutyTable.setText("生成考勤表");
        jButtonDutyTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDutyTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNewComerIput)
                    .addComponent(jButtonFormalStuTable))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNewToFormal)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonNewComerTable))
                    .addComponent(jButtonDutyTable))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewComerIput)
                    .addComponent(jButtonNewToFormal)
                    .addComponent(jButtonNewComerTable))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFormalStuTable)
                    .addComponent(jButtonDutyTable))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("学生管理", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("教师管理", jPanel4);

        jButtonCode.setText("编码查看与设置");
        jButtonCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButtonCode)
                .addContainerGap(486, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButtonCode)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("专业班级编码管理", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewToFormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewToFormalActionPerformed
        // TODO add your handling code here:
        newToFormalUI fr = new newToFormalUI(this);
        this.setVisible(false);
        fr.setVisible(true);
}//GEN-LAST:event_jButtonNewToFormalActionPerformed

    private void jButtonNewComerIputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewComerIputActionPerformed
        // TODO add your handling code here:
        newComerInputUI fr = new newComerInputUI(this);
        this.setVisible(false);//隐藏自己
        fr.setVisible(true);//显示子窗口
}//GEN-LAST:event_jButtonNewComerIputActionPerformed

    private void jButtonNewComerTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewComerTableActionPerformed
        // TODO add your handling code here:
        newComerTableDialog fr = new newComerTableDialog(this, true, this);
        //this.setVisible(false);//隐藏自己
        fr.setVisible(true);//显示子窗口
    }//GEN-LAST:event_jButtonNewComerTableActionPerformed

    private void jButtonDutyTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDutyTableActionPerformed
        // TODO add your handling code here:
        dutyTableDialog fr = new dutyTableDialog(this, true, this);
        fr.setVisible(true);
    }//GEN-LAST:event_jButtonDutyTableActionPerformed

    private void jButtonFormalStuTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormalStuTableActionPerformed
        // TODO add your handling code here:
        formalStuTableDialog fr = new formalStuTableDialog(this, true, this);
        fr.setVisible(true);
    }//GEN-LAST:event_jButtonFormalStuTableActionPerformed

    private void jButtonCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCodeActionPerformed
        // TODO add your handling code here:
        codecUI fr = new codecUI(this);
        this.setVisible(false);//隐藏自己
        fr.setVisible(true);//显示子窗口
    }//GEN-LAST:event_jButtonCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCode;
    private javax.swing.JButton jButtonDutyTable;
    private javax.swing.JButton jButtonFormalStuTable;
    private javax.swing.JButton jButtonNewComerIput;
    private javax.swing.JButton jButtonNewComerTable;
    private javax.swing.JButton jButtonNewToFormal;
    private javax.swing.JLabel jLabelTop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
